# Generated by Django 5.0.3 on 2024-04-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name=' Course ID')),
                ('course_code', models.CharField(max_length=255, verbose_name='Code')),
                ('course_name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Semester ID')),
                ('semester_year', models.DateField(verbose_name='Year')),
                ('semester_name', models.CharField(max_length=255, verbose_name='Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Student ID')),
                ('student_firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('student_lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('student_DOB', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Staff ID')),
                ('lecturer_firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lecturer_lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('lecturer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('lecturer_DOB', models.DateField(verbose_name='Date of Birth')),
                ('lecturer_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Enrollment',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(verbose_name='Number')),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.course', verbose_name='Course')),
                ('class_lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.lecturer', verbose_name='Lecturer')),
                ('class_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.semester', verbose_name='Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_year', models.IntegerField(verbose_name='Grade')),
                ('enrollment_date', models.DateField(verbose_name='Enrollment DateTime')),
                ('grade_date', models.DateField(verbose_name='Grade DateTime')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.class_enrollment', verbose_name='Class ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.student', verbose_name='Student ID')),
            ],
            options={
                'unique_together': {('student_id', 'class_id')},
            },
        ),
    ]
