# Generated by Django 5.0.3 on 2024-05-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_enrollment',
            old_name='grade_year',
            new_name='_grade',
        ),
    ]
