# Generated by Django 5.0.3 on 2024-04-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_alter_class_enrollment_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='staff_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Staff ID'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Semester ID'),
        ),
    ]
