# Generated by Django 5.0.3 on 2024-05-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_rename_grade_year_student_enrollment__grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_enrollment',
            old_name='_grade',
            new_name='student_grade',
        ),
    ]
